language: c
script:
  - echo ${TRAVIS_BUILD_DIR}
  - export LEARNING_STM32=${TRAVIS_BUILD_DIR}
  - arm-none-eabi-gcc --version
  - make

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded
